# Generated by Django 5.0.1 on 2024-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikpros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='nomdepot',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
