# Generated by Django 5.0.1 on 2024-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikpros', '0002_depot_nomdepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='emballage',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emballage',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nom_fournisseur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
