# Generated by Django 4.2.9 on 2024-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrikpros', '0003_emballage_designation_emballage_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
